[[exercises]]
name = "60_mini_shell"
title = "Mini Shell 2.0 增强版迷你 Shell"
unit = "unit3"
lesson = 60
order = 85
mode = "stdout"
source = "minishell2.c"
lesson_url = "https://cnb.cool/q.qq/opencamp-c-2026-summer/Unit-3-C-Classicals/-/tree/main/lessons/60_mini_shell"
hint = '''?????? README ? TODO ?????????????????????'''

[[exercises.cases]]
compile_only = true
