[[exercises]]
name = "54_json_parser"
title = "JSON Parser JSON 解析器"
unit = "unit3"
lesson = 54
order = 79
mode = "stdout"
source = "json_parser.c"
lesson_url = "https://cnb.cool/q.qq/opencamp-c-2026-summer/Unit-3-C-Classicals/-/tree/main/lessons/54_json_parser"
hint = '''?????? README ? TODO ?????????????????????'''

[[exercises.cases]]
compile_only = true
