[[exercises]]
name = "34_circular_list_josephus"
title = "约瑟夫环问题"
unit = "unit2"
lesson = 34
order = 59
mode = "stdout"
sources = ["main.c", "clist.c"]
lesson_url = "https://cnb.cool/q.qq/opencamp-c-2026-summer/Unit-2-C-Essentials/-/tree/main/lessons/34_circular_list_josephus"
hint = '''?????? README ? TODO ?????????????????????'''

[[exercises.cases]]
compile_only = true
