[[exercises]]
name = "65_elf_generator"
title = "ELF File Generator ELF文件生成器"
unit = "unit3"
lesson = 65
order = 90
mode = "stdout"
source = "elf_gen.c"
lesson_url = "https://cnb.cool/q.qq/opencamp-c-2026-summer/Unit-3-C-Classicals/-/tree/main/lessons/65_elf_generator"
hint = '''?????? README ? TODO ?????????????????????'''

[[exercises.cases]]
compile_only = true
