[[exercises]]
name = "27_sed_stream_editor"
title = "sed simple (简单流处理器实现和正则表达式)"
unit = "unit2"
lesson = 27
order = 52
mode = "stdout"
sources = ["main.c", "sed.c"]
lesson_url = "https://cnb.cool/q.qq/opencamp-c-2026-summer/Unit-2-C-Essentials/-/tree/main/lessons/27_sed_stream_editor"
hint = '''?????? README ? TODO ?????????????????????'''

[[exercises.cases]]
compile_only = true
