[[exercises]]
name = "29_more_command"
title = "more command (more命令实现)"
unit = "unit2"
lesson = 29
order = 54
mode = "stdout"
sources = ["main.c", "cmd_more.c"]
lesson_url = "https://cnb.cool/q.qq/opencamp-c-2026-summer/Unit-2-C-Essentials/-/tree/main/lessons/29_more_command"
hint = '''?????? README ? TODO ?????????????????????'''

[[exercises.cases]]
compile_only = true
