[[exercises]]
name = "58_http_server"
title = "Mini HTTP Server 迷你 HTTP 服务器"
unit = "unit3"
lesson = 58
order = 83
mode = "stdout"
source = "http_server.c"
lesson_url = "https://cnb.cool/q.qq/opencamp-c-2026-summer/Unit-3-C-Classicals/-/tree/main/lessons/58_http_server"
hint = '''?????? README ? TODO ?????????????????????'''

[[exercises.cases]]
compile_only = true
