[[exercises]]
name = "57_tcp_echo_server"
title = "Echo Server TCP 回声服务器"
unit = "unit3"
lesson = 57
order = 82
mode = "stdout"
source = "echo_server.c"
lesson_url = "https://cnb.cool/q.qq/opencamp-c-2026-summer/Unit-3-C-Classicals/-/tree/main/lessons/57_tcp_echo_server"
hint = '''?????? README ? TODO ?????????????????????'''

[[exercises.cases]]
compile_only = true
