[[exercises]]
name = "67_c_tokenizer"
title = "C Subset Tokenizer C子集词法分析器"
unit = "unit3"
lesson = 67
order = 92
mode = "stdout"
source = "tokenizer.c"
lesson_url = "https://cnb.cool/q.qq/opencamp-c-2026-summer/Unit-3-C-Classicals/-/tree/main/lessons/67_c_tokenizer"
hint = '''?????? README ? TODO ?????????????????????'''

[[exercises.cases]]
compile_only = true
