[[exercises]]
name = "61_riscv_assembly"
title = "RISC-V Assembly Primer RISC-V 汇编入门"
unit = "unit3"
lesson = 61
order = 86
mode = "make"
make_targets = ["all"]
timeout = 30
lesson_url = "https://cnb.cool/q.qq/opencamp-c-2026-summer/Unit-3-C-Classicals/-/tree/main/lessons/61_riscv_assembly"
hint = '''?????? README ? TODO ?????????????????????'''

[[exercises.cases]]
compile_only = true
