[[exercises]]
name = "26_elf_header_parser"
title = "ELF Header Parser (ELF文件头分析器实现)"
unit = "unit2"
lesson = 26
order = 51
mode = "stdout"
sources = ["main.c", "readelf.c"]
lesson_url = "https://cnb.cool/q.qq/opencamp-c-2026-summer/Unit-2-C-Essentials/-/tree/main/lessons/26_elf_header_parser"
hint = '''?????? README ? TODO ?????????????????????'''

[[exercises.cases]]
compile_only = true
