[[exercises]]
name = "62_instruction_encoder"
title = "RISC-V Instruction Encoder RISC-V 指令编码器"
unit = "unit3"
lesson = 62
order = 87
mode = "stdout"
source = "rv_encoder.c"
lesson_url = "https://cnb.cool/q.qq/opencamp-c-2026-summer/Unit-3-C-Classicals/-/tree/main/lessons/62_instruction_encoder"
hint = '''?????? README ? TODO ?????????????????????'''

[[exercises.cases]]
compile_only = true
