[[exercises]]
name = "53_base64_codec"
title = "Base64 Encoder/Decoder Base64 编解码"
unit = "unit3"
lesson = 53
order = 78
mode = "stdout"
source = "base64.c"
lesson_url = "https://cnb.cool/q.qq/opencamp-c-2026-summer/Unit-3-C-Classicals/-/tree/main/lessons/53_base64_codec"
hint = '''?????? README ? TODO ?????????????????????'''

[[exercises.cases]]
compile_only = true
