[[exercises]]
name = "64_assembler"
title = "Simple Assembler 简易汇编器"
unit = "unit3"
lesson = 64
order = 89
mode = "stdout"
source = "rv_asm.c"
lesson_url = "https://cnb.cool/q.qq/opencamp-c-2026-summer/Unit-3-C-Classicals/-/tree/main/lessons/64_assembler"
hint = '''?????? README ? TODO ?????????????????????'''

[[exercises.cases]]
compile_only = true
