[[exercises]]
name = "49_strip_comments_fsm"
title = "Delete Comments in C Program C程序去注释"
unit = "unit3"
lesson = 49
order = 74
mode = "stdout"
source = "strip_comments.c"
lesson_url = "https://cnb.cool/q.qq/opencamp-c-2026-summer/Unit-3-C-Classicals/-/tree/main/lessons/49_strip_comments_fsm"
hint = '''?????? README ? TODO ?????????????????????'''

[[exercises.cases]]
compile_only = true
