[[exercises]]
name = "50_regex_matcher"
title = "Regular Expression Matcher 正则表达式匹配器"
unit = "unit3"
lesson = 50
order = 75
mode = "stdout"
source = "regex.c"
lesson_url = "https://cnb.cool/q.qq/opencamp-c-2026-summer/Unit-3-C-Classicals/-/tree/main/lessons/50_regex_matcher"
hint = '''?????? README ? TODO ?????????????????????'''

[[exercises.cases]]
compile_only = true
